const pagesContants = {
    proyectsES: "productos",
    proyectsEN: "projects",
    nosotrosES: "nosotros",
    nosotrosEN: "about-us",
    prensaES: "prensa",
    prensaEN: "press",
    contactoES: "contacto",
    contactoEN: "contact",
    blogES: "blog",
    blogCategoriasES: "blog/categorias",
    blogCategoriasEN: "blog/categories",
    terminosCondicionesES: "terminos-y-condiciones",
    terminosCondicionesEN: "terms-and-conditions",
    avisoPrivacidadES: "aviso-de-privacidad",
    avisoPrivacidadEN: "privacy-notice",
    landingSelvaEscondidaIIES: "selvaescondida",
    landingSelvaEscondidaIIEN: "selvaescondida",
    landingSelvaEscondidaES: "selvaescondidaresidencial",
    landingSelvaEscondidaEN: "selvaescondidaresidencial",
    landingNaayES: "naay",
    landingPalmasES: "palmas",
    landingLuumES: "luum",
    landingKaanaES: "kaana",
    landingVeneciaES: "venecia",
    landingDelMarES: "delmar",
    landingEviaES: "evia",
    servicesEN: "services",
    servicesES: "servicios",
    cotizaEN: "quotation",
    cotizaES: "cotiza",
}

export default pagesContants;