const pagesContants = {
    proyectsES: "productos",
    proyectsEN: "projects",
    nosotrosES: "nosotros",
    ametek: "arizona",
    nosotrosEN: "about-us",
    prensaES: "prensa",
    prensaEN: "press",
    contactoES: "contacto",
    contactoEN: "contact",
    blogES: "blog",
    blogCategoriasES: "blog/categorias",
    blogCategoriasEN: "blog/categories",
    terminosCondicionesES: "terminos-y-condiciones",
    terminosCondicionesEN: "terms-and-conditions",
    avisoPrivacidadES: "aviso-de-privacidad",
    avisoPrivacidadEN: "privacy-notice",
    landingVelp: "velp",
    landingHitachi: "hitachi",
    landingLabindia: "labindia",
    landingAquaSolutions: "aqua-solutions",
    landingBwBTechnologies: "bwb-technologies",
    landingABB: "abb",
    landingOptosky: "optosky",
    landingAstori: "astori",
    servicesEN: "services",
    servicesES: "servicios",
    cotizaEN: "quotation",
    cotizaES: "cotiza",
}

export default pagesContants;