const apiHome = {
  items: [
    {
      type: "document-header-component",
      title: "Terms and conditions",
      description: `<span class="Al-usar-o-visitar-el-sitio-expresamente-manifiestas-tu-conform">
      By using or visiting the Site, you expressly agree and agree to be bound by the terms and conditions of this page, as well as all applicable laws and regulations in accordance with current legislation and applicable to the use of the Site. Desarrolladora Selva Escondida S.A. de C.V. and Studio Inmobiliario AP & DL S.A. de C.V., reserve the right to change these Terms and Conditions at any time, which will apply immediately after they have been published on the Site. Please visit this page of the Site regularly. If you violate these Conditions, Desarrolladora Selva Escondida S.A. de C.V. or Studio Inmobiliario AP & DL S.A. de C.V. may cancel your use of this Site, exclude you for future use of operations you intend to perform on the Site, cancel a purchase-sale transaction you have received through the Site, cancel your purchase-sale transaction, and/or take any legal action it deems appropriate for its interests.
        
      <br><br><h5><strong class="text-style-1">Permitted Use</strong></h5>
      You hereby fully acknowledge that you are only authorized to visit, view and consult the pages of this Site for your own use, and that you may not duplicate, download, publish, modify or otherwise distribute or alter the page content, or material contained on this Site for any purpose other than to review advertising information, for personal use, or for purchase and sale transactions or merchandise unless specifically authorized by Desarrolladora Selva Escondida S.A. de C.V. or Studio Inmobiliario AP & DL S.A. de C.V. The content and software on this Site is the property of Desarrolladora Selva Escondida S.A. de C.V. and Studio Inmobiliario AP & DL S.A. de C.V. and/or its suppliers and is protected under international and national copyright laws. We have posted a legal notice and various credits on the pages of the Site; these shall not be removed. Please do not remove this notice or these credits, or any additional information included with the notices and credits.
      
      <br><br><h5><strong class="text-style-1">Purchase and Sale Transaction Policy</strong></h5>
      Please review the Sales Policy, which governs your order or purchase on the Site.
      <br><br>
      Truthfulness and Accuracy of Information You Provide to Us; Compliance with Laws; Verifications and Authorizations.
    <br><br>    
    The purchase-sale transaction is regulated at the state, municipal or federal level. Bank fees are not generated by Desarrolladora Selva Escondida S.A. de C.V. / Studio Inmobiliario AP or DL S.A. de C.V. Likewise, any bank fees are non-refundable. You may be asked to provide certain information when involved in certain processes on the Site. You represent and warrant that all information you provide is true, complete, and correct, and that you will update all information as it changes. You also acknowledge that you will comply at all times with the terms, conditions and laws governing this service, and you agree to release Desarrolladora Selva Escondida S.A. de C.V. and Studio Inmobiliario AP & DL S.A. de C.V. from any liability, derived from the faults committed by you against any law, we will comply with the authorities that so require and we can provide them with all the information that you have sent us to help in any investigation or process that they can carry out. If we are unable to verify or verify the authenticity of any information you provide to us during any registration, order, purchase, posting of information, sale, verification of authenticity, delivery, payment or remittance process, or any other process not mentioned herein, or if we are unable to verify or authorize your credit card or bank account information, then you will be prohibited from using the Site.
    
    <br><br><h5><strong class="text-style-1">Links and Search Results</strong></h5>
    The Site may automatically produce search results that reference or link to third party sites throughout the World Wide Web. Desarrolladora Selva Escondida S.A. de C.V. or STUDIO INMOBILIARIO AP&DL S.A. DE C.V. have no control over these sites or their content. Desarrolladora Selva Escondida S.A. de C.V. and Studio Inmobiliario AP & DL S.A. de C.V. cannot guarantee, represent, or warrant that the content of these sites is accurate, legal and / or harmless. Desarrolladora Selva Escondida S.A. de C.V. and Studio Inmobiliario AP & DL S.A. de C.V. does not endorse the content of third-party sites, nor does it warrant that they will not contain viruses or otherwise impact your computer. By using this Site to perform searches or to link to another site, you agree and understand that you may not make any claim against Desarrolladora Selva Escondida S.A. de C.V. or Studio Inmobiliario AP & DL S.A. de C.V. for any damage or loss, whatever it may be, resulting from using the
    Site to obtain search results or links to another site. If you have a problem with a link from the Site, please send us an email.
    </span>`
    },
  ],
};

export default apiHome;
